
EVENT_WEIGHTS = {
    'ADLISTING/CLASSIFYAD_CLICK': 1.5, #1.5
    'ADLISTING/ADVIEW_CLICK': 1.5, #1.5
    'ADVIEW/SHOW_PHONE_CLICK': 2.5, #2.5
    'ADVIEW/SHOW_PHONE_CLICK_BODY': 2.5,#2.5
    'ADVIEW/CHAT_CLICK': 3,
    'ADVIEW/SMS_CLICK': 4,
    'ADVIEW/CALL_CLICK_BODY': 5,
    'ADVIEW/CALL_CLICK': 5
}