export const AUTHENTICATION_LOGIN="AUTHENTICATION::LOGIN";
export const AUTHENTICATION_LOADING="AUTHENTICATION::LOADING";
export const AUTHENTICATION_UNLOAD="AUTHENTICATION::UNLOAD";
export const AUTHENTICATION_SUCCESS="AUTHENTICATION::SUCCESS";
export const AUTHENTICATION_FAIL="AUTHENTICATION::FAIL";
export const AUTHENTICATION_CHECK_IF_LOGGED_IN="AUTHENTICATION::CHECK_IF_LOGGED_IN";
export const AUTHENTICATION_LOGOUT="AUTHENTICATION::LOGOUT";